server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_login_facebook
    username: root
    password: 11041998bkhn

  thymeleaf:
    cache: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 3233182393440093
            clientSecret: ce6c2ce1b6716d0865c70901a158b880
            scope:
              - email
              - public_profile


